version: '3.8'

services:

  app:
    container_name: symfony
    image: alievna/symfony:latest
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:symfony_password@db:3306/symfony?serverVersion=mariadb-11.4.2&charset=utf8mb4"

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

