services:
  app:
    container_name: symfony
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - symfony-network

  db:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: symfony
      MARIADB_USER: username
      MARIADB_PASSWORD: password
    networks:
      - symfony-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 3307:8080
    networks:
      - symfony-network

networks:
  symfony-network:
