version: '3.8'

services:

  app:
    container_name: symfony
    image: alievna/symfony:latest
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: symfony
      MARIADB_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

