services:

  app:
    container_name: symfony
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: symfony
      MARIADB_USER: user
      MARIADB_PASSWORD: password

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 3307:8080

volumes:
  db_data:

