name: Deploy to Dev Server

on:
  push:
    branches:
      - develop

jobs:

  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into server and run Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            if [ ! -d "/var/www/symfony-ci-cd" ]; then
              git clone https://github.com/Musa-f/symfony-ci-cd /var/www/
            fi
            cd /var/www/symfony-ci-cd/docker
            git checkout develop
            git pull origin develop
            cd /var/www/symfony-ci-cd/docker
            docker compose pull
            docker compose down
            docker compose up -d

  tests:
    needs: update

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  QA:
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
