name: Deploy to Dev Server

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: symfony
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=30s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare test database
        run: |
          mysql -h localhost -u $MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE DATABASE IF NOT EXISTS symfony"

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

  # test-services:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install dependencies
  #       uses: php-actions/composer@v6

  #     - name: PHPUnit Tests for Services
  #       uses: php-actions/phpunit@v3
  #       with:
  #         version: 9.6
  #         bootstrap: vendor/autoload.php
  #         configuration: tests/phpunit.xml
  #         args: --testsuite=Services

  # test-controllers:
  #   needs: [test-services]
  #   runs-on: ubuntu-latest

  #   services:
  #     mariadb:
  #       image: mariadb:latest
  #       env:
  #         MARIADB_ROOT_PASSWORD: toor
  #         MARIADB_DATABASE: test
  #         MARIADB_USER: test
  #         MARIADB_PASSWORD: test
  #       ports:
  #         - 3306:3306
  #       options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
                
  #   env:
  #     BDD_HOST: 127.0.0.1
  #     BBD_PORT: 3306
  #     BDD_NAME: test
  #     BDD_USER: test
  #     BDD_PASS: test

  #   steps:
  #   - name: PHPUnit Tests for Controllers
  #     uses: php-actions/phpunit@v3
  #     with:
  #       version: 9.6
  #       bootstrap: vendor/autoload.php
  #       configuration: tests/phpunit.xml
  #       args: --testsuite=Controllers

# tests:
#     needs: update
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run tests
#         uses: ./.github/workflows/tests.yml

#   qa:
#     needs: tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run QA checks
#         uses: ./.github/workflows/qa.yml

# update:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: SSH into server and run Docker Compose
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         password: ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: ${{ secrets.SERVER_SSH_PORT }}
  #         script: |
  #           cd /var/www/symfony-ci-cd
  #           git checkout develop
  #           git pull origin develop
  #           docker compose -f ./docker/docker-compose.yml up -d --build

#   merge:
#     needs: qa
#     runs-on: ubuntu-latest
#     if: success()
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Merge develop into release
#         run: |
#           git checkout release
#           git merge develop
#           git push origin release