name: Deploy to Dev Server

on:
  push:
    branches:
      - develop

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          version: 9.6
          php_version: 8.3
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

  # update:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: SSH into server and run Docker Compose
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         password: ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: ${{ secrets.SERVER_SSH_PORT }}
  #         script: |
  #           cd /var/www/symfony-ci-cd
  #           git checkout develop
  #           git pull origin develop
  #           docker compose -f ./docker/docker-compose.yml up -d --build

#FIXME FONCTIONNE SUR LE SEVEUR MAIS PAS SUR LE WORKFLOW
      # - name: Run migrations
      #   run: |
      #     docker exec symfony bin/console doctrine:migrations:migrate

  # tests:
  #     needs: update
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Run tests
  #         uses: ./.github/workflows/tests.yml

#   qa:
#     needs: tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run QA checks
#         uses: ./.github/workflows/qa.yml

#   merge:
#     needs: qa
#     runs-on: ubuntu-latest
#     if: success()
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Merge develop into release
#         run: |
#           git checkout release
#           git merge develop
#           git push origin release