name: Deploy to Preprod Server

on:
  push:

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches and tags from origin
        run: git fetch --prune --unshallow

      - name: Checkout develop branch
        run: |
          git checkout develop

      - name: Create or update release branch
        run: |
          if git show-ref --verify --quiet refs/heads/release; then
            git checkout release
            git pull origin release 
            git merge develop --no-ff -m "Merging changes from develop to release"
          else
            git checkout -b release develop
          fi
          
      - name: Push release branch
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git push origin release

  update-docker:
    runs-on: ubuntu-latest
    needs: merge-branch 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t alievna/ressources-relationnelles:${GITHUB_SHA} -f ./docker/Dockerfile .
          docker push alievna/ressources-relationnelles:${GITHUB_SHA}


  # test-services:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '8.2'

  #     - name: Install dependencies
  #       uses: php-actions/composer@v6

  #     - name: Run PHPUnit tests
  #       run: php ./vendor/bin/phpunit --testsuite=Services --configuration tests/phpunit.xml

  # test-routes:
  #   runs-on: ubuntu-latest

  #   services:
  #     mariadb:
  #       image: mariadb:10.5
  #       env:
  #         MARIADB_ROOT_PASSWORD: root
  #         MARIADB_DATABASE: symfony_test
  #         MARIADB_USER: symfony
  #         MARIADB_PASSWORD: symfony
  #       ports:
  #         - 3306:3306
  #       options: >-
  #         --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
  #         --health-interval=10s
  #         --health-timeout=5s
  #         --health-retries=3

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '8.2'

  #     - name: Start MariaDB
  #       run: |
  #         for i in `seq 1 30`; do
  #           if mysqladmin ping -h "127.0.0.1" --silent; then
  #             echo "MariaDB is ready!"
  #             break
  #           fi
  #           echo 'Waiting for MariaDB...'
  #           sleep 2
  #         done

  #     - name: Install dependencies
  #       uses: php-actions/composer@v6

  #     - name: Prepare database
  #       env:
  #         DATABASE_URL: mysql://symfony:symfony@127.0.0.1:3306/symfony_test
  #       run: |
  #         php bin/console doctrine:schema:update --force
  #         php bin/console doctrine:fixtures:load --no-interaction

  #     - name: Run PHPUnit tests
  #       run: php ./vendor/bin/phpunit --testsuite=Controllers --configuration tests/phpunit.xml

  # merge:
  #   needs: [test-services, test-routes]
  #   runs-on: ubuntu-latest
  #   if: success()
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0 

  #     - name: Fetch all branches
  #       run: git fetch origin

  #     - name: Checkout release branch
  #       run: git checkout -b release origin/release

  #     - name: Merge develop into release
  #       run: |
  #         git merge develop
  #         git push origin release



# update:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: SSH into server and run Docker Compose
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         password: ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: ${{ secrets.SERVER_SSH_PORT }}
  #         script: |
  #           cd /var/www/symfony-ci-cd
  #           git checkout develop
  #           git pull origin develop
  #           docker compose -f ./docker/docker-compose.yml up -d --build

