name: Deploy to Dev Server

on:
  push:
    branches:
      - develop

jobs:

  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into server and run Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/www/symfony-ci-cd
            git checkout develop
            git pull origin develop
            docker compose -f ./docker/docker-compose.yml up -d --build

      # - name: Run Doctrine Migrations
      #   uses: docker://php
      #   with:
      #     entrypoint: sh
      #     args: -c "docker run --rm -v $PWD:/app -w /app php php bin/console doctrine:migrations:migrate"

      # - name: Load Doctrine Fixtures
      #   if: success() && steps.ssh-exec.outcome == 'success'

  # tests:
  #   needs: update
  #   uses: ./.github/workflows/tests.yml

  # QA:
  #   needs: tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
