name: Deploy to Dev Server

on:
  push:
    branches:
      - develop

jobs:

  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH connection and update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            if [ ! -d "/var/www/symfony-ci-cd" ]; then
              git clone https://github.com/Musa-f/symfony-ci-cd /var/www/
            fi
            cd /var/www/symfony-ci-cd
            git checkout develop
            git pull origin develop

      - name: Docker update
        run: |
          cd /var/www/symfony-ci-cd
          docker-compose -f ./docker/docker-compose.yml up -d --build

      # - name: Run Doctrine Migrations
      #   if: success() && steps.ssh-exec.outcome == 'success'

      # - name: Load Doctrine Fixtures
      #   if: success() && steps.ssh-exec.outcome == 'success'

  # tests:
  #   needs: update
  #   uses: ./.github/workflows/tests.yml

  # QA:
  #   needs: tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
