name: PHPUnit Tests

on:
    workflow_call

jobs:
  test_services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHPUnit Tests for Services
        run: vendor/bin/phpunit --testsuite=services

  test_controllers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHPUnit Tests for Controllers
        run: vendor/bin/phpunit --testsuite=controllers
